import { Product } from "@/types";

export const products: Product[] = [
  {
    id: "1",
    title: "The Art of Focus",
    author: "Sara Lin",
    price: 14.99,
    discount: 0.2,
    genre: "Self-Help",
    description: "A practical guide to mastering concentration in a digital world. Learn proven techniques to minimize distractions, enhance productivity, and achieve deep work.",
    coverImage: "https://placehold.co/400x600/6366f1/ffffff?text=The+Art+of+Focus&font=poppins",
    format: "EPUB",
    rating: 4.7,
    pages: 210,
    language: "English",
    releaseDate: "2022-03-01"
  },
  {
    id: "2",
    title: "Travel Memories",
    author: "James Wilson",
    price: 12.99,
    discount: 0,
    genre: "Travel",
    description: "Stunning photography and inspiring stories from around the world. Discover hidden gems and must-visit destinations for your next adventure.",
    coverImage: "https://placehold.co/400x600/059669/ffffff?text=Travel+Memories&font=poppins",
    format: "PDF",
    rating: 4.8,
    pages: 320,
    language: "English",
    releaseDate: "2023-05-15"
  },
  {
    id: "3",
    title: "Digital Nomad Handbook",
    author: "Maya Chen",
    price: 16.99,
    discount: 0.15,
    genre: "Lifestyle",
    description: "Everything you need to know about working remotely while traveling. From visa requirements to finding the best coworking spaces.",
    coverImage: "https://placehold.co/400x600/dc2626/ffffff?text=Digital+Nomad+Handbook&font=poppins",
    format: "EPUB",
    rating: 4.6,
    pages: 280,
    language: "English",
    releaseDate: "2023-08-20"
  },
  {
    id: "4",
    title: "Budget Travel Guide",
    author: "David Park",
    price: 9.99,
    discount: 0.3,
    genre: "Travel",
    description: "Learn how to see the world on a shoestring budget. Discover money-saving tips, cheap accommodation options, and travel hacks.",
    coverImage: "https://placehold.co/400x600/f59e0b/ffffff?text=Budget+Travel+Guide&font=poppins",
    format: "EPUB",
    rating: 4.5,
    pages: 190,
    language: "English",
    releaseDate: "2022-11-10"
  },
  {
    id: "5",
    title: "Photography on the Road",
    author: "Emma Rodriguez",
    price: 19.99,
    discount: 0.1,
    genre: "Photography",
    description: "Capture stunning travel photos with any camera. Techniques, composition tips, and post-processing guides for travel photographers.",
    coverImage: "https://placehold.co/400x600/7c3aed/ffffff?text=Photography+on+the+Road&font=poppins",
    format: "PDF",
    rating: 4.9,
    pages: 350,
    language: "English",
    releaseDate: "2024-01-05"
  },
  {
    id: "6",
    title: "Solo Travel: A Journey Within",
    author: "Alex Kim",
    price: 13.99,
    discount: 0,
    genre: "Travel",
    description: "Inspiring stories and practical advice for solo travelers. Overcome fears, build confidence, and embrace the freedom of traveling alone.",
    coverImage: "https://placehold.co/400x600/ec4899/ffffff?text=Solo+Travel&font=poppins",
    format: "EPUB",
    rating: 4.7,
    pages: 240,
    language: "English",
    releaseDate: "2023-02-14"
  },
  {
    id: "7",
    title: "Cultural Immersion",
    author: "Sophie Thompson",
    price: 15.99,
    discount: 0.25,
    genre: "Culture",
    description: "Go beyond tourism and truly connect with local cultures. Learn customs, traditions, and how to travel respectfully around the world.",
    coverImage: "https://placehold.co/400x600/0891b2/ffffff?text=Cultural+Immersion&font=poppins",
    format: "EPUB",
    rating: 4.6,
    pages: 270,
    language: "English",
    releaseDate: "2023-06-30"
  },
  {
    id: "8",
    title: "Sustainable Travel",
    author: "Dr. Maria Santos",
    price: 17.99,
    discount: 0,
    genre: "Environment",
    description: "Travel responsibly and reduce your environmental impact. Eco-friendly destinations, carbon offsets, and sustainable practices for conscious travelers.",
    coverImage: "https://placehold.co/400x600/16a34a/ffffff?text=Sustainable+Travel&font=poppins",
    format: "PDF",
    rating: 4.8,
    pages: 310,
    language: "English",
    releaseDate: "2024-02-01"
  },
  {
    id: "9",
    title: "Mindful Journeys",
    author: "Lisa Anderson",
    price: 18.99,
    discount: 0.2,
    genre: "Self-Help",
    description: "Combine mindfulness practices with travel for transformative experiences. Learn meditation techniques and mindfulness exercises for your journeys.",
    coverImage: "https://placehold.co/400x600/be123c/ffffff?text=Mindful+Journeys&font=poppins",
    format: "EPUB",
    rating: 4.9,
    pages: 290,
    language: "English",
    releaseDate: "2023-09-12"
  },
  {
    id: "10",
    title: "Hidden Gems of Europe",
    author: "Roberto Silva",
    price: 15.99,
    discount: 0,
    genre: "Travel",
    description: "Discover off-the-beaten-path destinations across Europe. Insider tips from locals and hidden spots that tourists rarely find.",
    coverImage: "https://placehold.co/400x600/c2410c/ffffff?text=Hidden+Gems+of+Europe&font=poppins",
    format: "EPUB",
    rating: 4.8,
    pages: 380,
    language: "English",
    releaseDate: "2023-12-01"
  },
  {
    id: "11",
    title: "Backpacking Asia",
    author: "Wang Wei",
    price: 14.99,
    discount: 0.15,
    genre: "Travel",
    description: "Complete guide to backpacking through Southeast Asia. Budget tips, route planning, cultural insights, and must-see destinations.",
    coverImage: "https://placehold.co/400x600/eab308/ffffff?text=Backpacking+Asia&font=poppins",
    format: "EPUB",
    rating: 4.7,
    pages: 420,
    language: "English",
    releaseDate: "2023-07-20"
  },
  {
    id: "12",
    title: "Coastal Escapes",
    author: "Sarah Martinez",
    price: 13.99,
    discount: 0.1,
    genre: "Travel",
    description: "Beautiful coastal destinations around the world. Beach towns, island paradises, and seaside adventures for every type of traveler.",
    coverImage: "https://placehold.co/400x600/0284c7/ffffff?text=Coastal+Escapes&font=poppins",
    format: "PDF",
    rating: 4.6,
    pages: 330,
    language: "English",
    releaseDate: "2024-03-15"
  },
  {
    id: "13",
    title: "Mountain Adventures",
    author: "Jack Thompson",
    price: 16.99,
    discount: 0,
    genre: "Travel",
    description: "Epic mountain destinations for hikers, climbers, and nature lovers. Safety tips, gear guides, and breathtaking trails.",
    coverImage: "https://placehold.co/400x600/166534/ffffff?text=Mountain+Adventures&font=poppins",
    format: "EPUB",
    rating: 4.9,
    pages: 360,
    language: "English",
    releaseDate: "2023-10-08"
  },
  {
    id: "14",
    title: "City Break Guide",
    author: "Emma Watson",
    price: 11.99,
    discount: 0.25,
    genre: "Travel",
    description: "Maximize short city trips with curated itineraries. Weekend guides for major cities worldwide with insider recommendations.",
    coverImage: "https://placehold.co/400x600/991b1b/ffffff?text=City+Break+Guide&font=poppins",
    format: "EPUB",
    rating: 4.5,
    pages: 250,
    language: "English",
    releaseDate: "2023-04-22"
  },
  {
    id: "15",
    title: "Adventure Photography",
    author: "Michael Chang",
    price: 20.99,
    discount: 0.15,
    genre: "Photography",
    description: "Advanced techniques for capturing breathtaking adventure photos. Landscape, action, and wildlife photography in challenging conditions.",
    coverImage: "https://placehold.co/400x600/6b21a8/ffffff?text=Adventure+Photography&font=poppins",
    format: "PDF",
    rating: 4.8,
    pages: 410,
    language: "English",
    releaseDate: "2024-01-18"
  },
  {
    id: "16",
    title: "Food & Travel Journal",
    author: "Isabella Garcia",
    price: 17.99,
    discount: 0,
    genre: "Culture",
    description: "Explore the world through its cuisine. Food tours, cooking classes, local markets, and authentic dining experiences from global destinations.",
    coverImage: "https://placehold.co/400x600/be185d/ffffff?text=Food+%26+Travel+Journal&font=poppins",
    format: "EPUB",
    rating: 4.7,
    pages: 300,
    language: "English",
    releaseDate: "2023-11-30"
  }
];
